### ISSUE TITLE
Building assessment: Undefined variables and attributes

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1375]
When the *Building Assessment* module is enabled, visiting its index throws error
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/building.py", line 172, in <module>
    represent = s3_yes_no_represent),
NameError: name 's3_yes_no_represent' is not defined
```

This is likely caused by missing import in the beginning of *controllers/building.py*
```python
from s3 import s3_yes_no_represent
```

After this addition, the module starts throwing a diferent error.
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/building.py", line 275, in <module>
    building_nzseel1_search = s3base.S3Search(
AttributeError: 'module' object has no attribute 'S3Search'
```
which seems to be some regression as `S3Search` isn't defined anywhere.

I'm aware that the module is outdated and there is a ToDo to merge it into *Survey* module, however the *Building Assessment* module is not marked as obsolete yet.

**Comment by flavour** [comment]
Correct analysis, this module was written for NZ Canterbury EQ and hasn't been touched since other than a very simple rough migration through 1 evolution of code.
The yes_no_represent is easy to fix indeed.
S3Search had been replaced by S3Filter, which is a bit more work to migrate to, but still fairly easy for anyone who wishes to make use of this module :)
