### ISSUE TITLE
Error when hard deleting organisation

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1377]
When `settings.security.archive_not_delete = False` and organisation has any dependent record (office, warehouse, facility, staff, volunteers, ...), deleting such organisation fails with following error
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/org.py", line 481, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/org.py", line 193, in organisation
    return s3db.org_organisation_controller()
  File "applications/eden/modules/s3db/org.py", line 6801, in org_organisation_controller
    rheader = org_rheader,
  File "/srv/sahana/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1774, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 99, in apply_method
    output = self.delete(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 1041, in delete
    numrows = self.resource.delete(format=r.representation)
  File "applications/eden/modules/s3/s3resource.py", line 1052, in delete
    if not deletable:
UnboundLocalError: local variable 'deletable' referenced before assignment
```

The conflicting part starting on line 1044 in *s3resource.py* looks as follows 
```python
        if numrows == 0:
            if not deletable:
                # No deletable rows found
                self.error = INTEGRITY_ERROR
            elif permission_error:
                # Deletion failed due to insufficient permissions
                self.error = current.ERROR.NOT_PERMITTED
```
This suggest, that the `numrows == 0` condition evaluates to `True` and the program flow enters its body, where the unassigned variable `deletable` is used. The variable with the same name gets populated in the code above, but in different scope.

This problem exist only with hard deletes. The soft deletes correctly throw an integrity error in user-friendly popup box.

**Comment by nursix** [comment]
Deletion hasn't been tested for ages - since nobody is actually using it ;)

However - clearly a bug, albeit easy to fix: 
Record deletion (unlike record archiving) assumes deletable=len(rows), and for every failure ("Row is not deletable") would subtract 1. If that gives zero, then that means "no deletable rows found".

Will fix this.

**Comment by nursix** [comment]
Fix provided:
https://github.com/nursix/eden/commit/e4698399de6c5b9540a5850e9576d0be9baf7180

**Comment by trendspotter** [comment]
Hard-deleting organisations which are referenced now gracefully fails with user-friendly error in popup box. Thanks.

**Comment by nursix** [comment]
NB "hard-deleting" is not recommended for production deployments, and it will not work effectively if you have multiple synchronized instances (peers can't see hard-deletions, so they would restore what you delete). It is also not sufficiently tested across the board.

If there is a specific reason to deploy with deletion instead of archiving, then it would be interesting to learn about it - this requirement hasn't come up in a decade (if-ever).
