### ISSUE TITLE
CAP: String encoding mixing in cap_alert_list_layout (and possibly elsewhere)

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1382]
I’m opening this as an issue rather than PR, as I'm not entirely sure if my idea of fixing is correct.

**Steps to reproduce:**
1. Install SAMBRO template
2. Have a language with translated string `"Issued by"` where the translation contains unicode characters (yes, very specific :) )
3. Enable that language
4. Visit URL `/eden/default/index/alert_hub_cop`

**Observed behavior:**
SE throws following stack trace
```
Traceback (most recent call last):
  File "/srv/sambro/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sambro/applications/eden/controllers/default.py", line 1547, in <module>
  File "/srv/sambro/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sambro/applications/eden/controllers/default.py", line 114, in index
    output = controller()
  File "applications/eden/modules/templates/SAMBRO/controllers.py", line 1685, in __call__
    pagesize = 0,
  File "applications/eden/modules/s3/s3data.py", line 1055, in html
    record)
  File "applications/eden/modules/s3db/cap.py", line 4019, in cap_alert_list_layout
    issuer = "%s: %s" % (T("Issued by"), sender_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

**Short analysis:**
Now, the problem is, that the `T()` function lazily returns *str* whereas `sender_name` variable is *unicode*. However when a *str* contains encoded unicode characters, python 2 (I have 2.7.13) refuses to format it in the same string together with pure *unicode*.

This is OK: `print '%s: %s' % ('a', u'b')` (ascii w/o unicode + unicode)  
This is OK: `print '%s: %s' % ('á', 'b')` (ascii w/ unicode + ascii w/o unicode)  
This is OK: `print '%s: %s' % (u'á', u'b')` (unicode + unicode)  
This is **not** OK: `print '%s: %s' % ('á', u'b')` (ascii w/ unicode + unicode)  
Strangely enough, PEP 3101 way of formating is OK too: `print '{}: {}'.format('á', u'b')`

**Proposed solution:**
The simplest and least painful fix seems to be to replace line 4001 in *modules/s3db/cap.py*
```python
sender_name = record["cap_info.sender_name"]
```
with
```python
sender_name = s3_str(record["cap_info.sender_name"])
```

However I'm not sure if this is the right thing to do, as the same value in the other condition branch remains unchanged (which probably doesn't matter as there is no string formatting). Moreover there may be more unicode variables which I haven't encountered yet, so my solution is not systematic enough.

**Comment by flavour** [comment]
The s3_str method is exactly what is used elsewhere.
Am not sure how we can be more systematic without patching web2py

**Comment by nursix** [comment]
Yeah - the unicode mess!

I agree, just patching in s3_str is cheap and effective - but it's not really systematic.

Some background:
- we shall try to normalize any handover (parameter or return) of strings to utf-8 encoded str
- avoid unicode unless you need it (temporarily)
- unicode is needed when you parse, split, replace, lower/upper etc - and then it is a *must*!
- we have "safe" converters for both directions: s3_str and s3_unicode (both assuming utf-8)

For represented values, however, character-operations are extremely rare, so returning unicode from a representation function doesn't normally make sense. It's the easy way, though, because the DAL delivers unicode and just returning that is the obvious thing to do.

Now, there is already a general requirement for all representation functions to always return utf-8 encoded str - and it's been implemented in S3Represent (so much for "systematic" approaches).

And the point with that is exactly this: the HTML construction helpers apply str() on everything (i.e. using ASCII codec), so they will almost always crash with unicodes beyond ASCII. Represented values almost always go into HTML (what else is the point?), hence we want str from all represents.

Now...one systematic violation of this rule is the default renderer in S3ResourceData (my fault, sorry, fix pushed).

But note: even if that fixes a whole bunch of cases, it doesn't mean it fixes /all/ cases. This problem will probably haunt us as long as we use Py-2.7 ;)

**Comment by nursix** [comment]
@trendspotter 

You may want to test again once this is merged:
https://github.com/nursix/eden/commit/0df0a3aaf3e78b72fc674dc8b45c69e353cf6b23

...before you put in that s3_str. Maybe (hopefully) you don't need it anymore then.

**Comment by trendspotter** [comment]
Confirmed. Alert hub is now displayed properly even without the explicit *s3_str()*. Thanks.

**Comment by nursix** [comment]
Cool, so I dare closing this then...
