### ISSUE TITLE
Staff import fails when settings.hrm.staff_label is set

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1385]
When `settings.hrm.staff_label = "Contacts"` (or any other non-default value), import of staff / contacts sheet will always fail with following validation error
```
hrm_human_resource: Validation error
type: Value not allowed
```
In the import overview, the `hrm_human_resource.type` is showing `Contacts` which suggests that the import validation routine didn't get the memo about the adjusted label (resp. type), otherwise it would probably show `hrm_human_resource.type: 1` as it does when `settings.hrm.staff_label` is kept in default.

Example sheet which triggers the error is as follows:
```csv
Organisation,Department,First Name,Last Name,Email,Office Phone
Test Organisation,Test Department 1,Jane,Doe,jane.doe@example.com,+123456789012
Test Organisation,Test Department 2,John,Doe,john.doe@example.com,+123456789013
Test Organisation,Test Department 3,John,Smith,john.smith@example.com,+123456789014
```

On slightly related note - The department name is limited only to 64 characters, which seems like awfully small number as the government organizations are infamous for names like "Department of Civil Emergency Planning, Protection of Classified Information, Defense and Defense Planning" (not making this up, we have plenty like this). Even the organisation name is limited to 128 characters.

**Comment by nursix** [comment]
NB the header of the corresponding XSLT clearly documents the accepted options for this column:

https://github.com/sahana/eden/blob/master/static/formats/s3csv/hrm/person.xsl#L15

**Comment by trendspotter** [comment]
Okay. The template CSV does not contain the *Type* column and it didn't occur to me to check also XSLT.

As for the long names - understood and agreed. Let's see what can we abbreviate.

Thanks.

**Comment by nursix** [comment]
Yeah, CSV/XLS formats are a common point of contention - simply because everybody want something else. But exactly that is the problem with Spreadsheets in general ;)

Whilst there is some flexibility in the CSV formats, our standpoint tends to be that it is easier to fix CSV/XLS sheets to meet a standard format, than it is to implement complex data analysis/interpretation in the importer....which is only bound to fail again with the next user who wants something differently.

But you're right, it's not obvious that you should look into the XSLT to see the documentation for the CSV format ;) that's just something you need to know. The XSLT files are easy to find - they have the same name as the CSV template, and are in the same folder.

It might be possible to write a function that extracts the documentation from the XSLT and shows it as a "Help" link beside the download-link for the CSV template - if you like the idea, then feel free to add it as a new issue. Or else - make a better proposal ;)
