### ISSUE TITLE
Map profile not showing organization

### ISSUE THREAD

**Issue by preetime28** [sahana/eden#1425]
I added an organization (say org X) using org module. Then I created an user and assign him to the org X. Then in map profile, I tried to create a profile of the organization. However, the `Person or OU` field is only loading person and not the org X. Is this the default behaviour? How do I create map profile for the organization so that every user of the organization get the map profile of the organization?

**Comment by nursix** [comment]
Yes, it's the default behavior - but probably not how this is intended to work.

The form field is configured here:
https://github.com/sahana/eden/blob/master/modules/s3db/gis.py#L2083

...using the generic S3AutocompleteWidget. The client-side script of this widget calls this request handler:
https://github.com/sahana/eden/blob/master/modules/s3db/pr.py#L450

...but it doesn't specify which entity types to look for, so it falls back to just Persons+Groups:
https://github.com/sahana/eden/blob/master/modules/s3db/pr.py#L476

Instead of using the generic S3AutoCompleteWidget, the form field should probably be configured with this:
https://github.com/sahana/eden/blob/master/modules/s3/s3widgets.py#L8332
...which allows to specify the entity types that shall be selectable, so organizations can be added.

However, I'm not sure whether this is the correct approach - would like to hear @flavour 's opinion before attempting to fix it. I'm wondering whether an organization's map configuration actually does propagate to all users of the org (I guess it does?) - and if yes, then how are org map configurations normally managed?

**Comment by flavour** [comment]
You have the correct analysis.
Org Map profiles *do* propagate to all users
Usually set via Prepop rather than UI which is why the UI not allowing this hasn't been an issue before, despite the feature being used.
