### ISSUE TITLE
Supply/ItemsAlt/Item popup not closing after submission

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1472]
Currently observed in *Warehouse* while adding items and in *Projects* while adding a region.

Steps to reproduce:
1. Create and item in supply module (`/eden/supply/item/create`).
2. Open the newly create item and go to *Alternative Items* tab.
3. Click *Create Alternative Item* and then on *Create Item* next to the *Item* field, a popup will open.
4. Fill in the popup form and click *Save*.

Expected result:
Item is created and popup closed.

Actual result:
Item is create but popup stays visible with message "Submission successful - please wait...". There is also a related *404 - Not Found* error visible in request log and error console for `/eden/supply/item_alt_alt/options.s3json?field=item_id&only_last=1`.

**Comment by nursix** [comment]
Working on that at the moment anyway, so will fix. Thanks for reporting.

**Comment by nursix** [comment]
For Alternative Items, I could reproduce the problem and fix it.

For "regions" in Projects I'm not sure what you're referring to - maybe you can provide some "Steps to reproduce" for that too? (can't find any "regions" in project)

**Comment by nursix** [comment]
In case you want to fix this kind of problem yourself:

This happens mostly if the calling field (the one that has the Add-link) has a non-default field name, but the Add-link doesn't specify that name as "child" parameter.

A typical scenario is that the field is defined with an S3ReusableField, overriding the name. In these cases, the popup-link is often forgotten.

Take the "Alternative Items" case as an example:

The field ```alt_item_id``` is defined using the ```supply_item_id``` re-usable field variable:
https://github.com/sahana/eden/blob/master/modules/s3db/supply.py#L810
...renaming it as "alt_item_id".

This re-usable field is defined here, and it includes a popup link:
https://github.com/sahana/eden/blob/master/modules/s3db/supply.py#L467

The standard field name for a ```supply_item``` reference would be ```item_id```, and this is what the popup-script will assume when inferring a URL to look-up the (updated) options for the caller field.

But if the actual field name deviates from this standard, then this URL construction will produce nonsense - so the look-up will fail and prevent the popup from closing.

However, it is possible to override this assumption by adding an explicit ```child``` parameter to the popup link, specifying the actual field name.

Obviously, we can't do this here in the re-usable field (because it is indeed defined as "item_id"):
https://github.com/sahana/eden/blob/master/modules/s3db/supply.py#L467

...but must override the entire popup link in the place where the Field is instantiated with a different name:
https://github.com/nursix/eden/commit/7ae0dbe7c7bd8d7e363734cf259c239a5c35959f#diff-8c3ded65fc431ebb6b1bd9307ed5a1ebR811
...and there we can add the ```child``` parameter.

There could be other places with such issues, and it is likely that they show a similar pattern. And if the corresponding field is exposed, then they should be fixed.

This isn't easy to see, admittedly - but if you know what it is about, then it is actually easy to fix. So, if you want to take a look around and see if you can spot some more...I'd be looking forward to your PR then.

**Comment by trendspotter** [comment]
Yeah, sorry about being so vague on the other case, I didn't have exact info at the time. It's possible that it is a completely different problem though.

Just a short explanation - We have a staging instance with customized template where we're testing all the functionality and continuously simulate actual use (*breeding the bugs* :) ) and then we have another instance with clean *default* template where we're trying to replicate the exact conditions for the problems we're reporting, just to see if it's actually a problem in the code or if it's just a misconfiguration on our part. With the other case of popup not closing, I'm having a hard time to replicate the exact condition on a clean instance.

So far, I can give you steps to reproduce as:
1. Set `settings.org.regions = True`, `settings.org.regions_hierarchical = True` and `settings.project.mode_3w = True`
2. Navigate to *Projects* and select *Partner Organization* -> *Create*
3. Click on *Add Region* next to the *Region* field
4. Fill in the region and click *Save*

Although at this point the steps are incomplete as there is some more settings which needs to be set in order to trigger the failure which I have yet to find.

And apart from the popup not closing I'm getting also following trace in browser console:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (jquery-1.11.3.js:358)
    at Object.<anonymous> (VM489 s3.popup.js:287)
    at Object.AjaxS3.onSuccess (S3.js:611)
    at Object.<anonymous> (S3.js:721)
    at fire (jquery-1.11.3.js:3148)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.js:3260)
    at done (jquery-1.11.3.js:9314)
    at XMLHttpRequest.callback (jquery-1.11.3.js:9718)
```

Also, strangely enough, the error does not occur with the exact same popup in *Organizations* -> *Create Organization*.

Once I'll have something more definite to go on, I'll update the issue. (Unless you manage to go on and find the culprit based on what I've given above.)

**Comment by nursix** [comment]
Okay - this would be a separate issue, as it doesn't seem to have the same underlying cause. Could you pls open a new one for the Project/PartnerOrg/Region problem?

**Comment by nursix** [comment]
And yes, your description above is good enough for me to find the cause. Just move it into a separate issue. Thx.

**Comment by trendspotter** [comment]
...and yup, I confirm that https://github.com/nursix/eden/commit/d5b376234d5e473c89a04e53b79a8e09b4439cfe resolves the issue with alternative items. Thanks.
