### ISSUE TITLE
Contributing + technical debt

### ISSUE THREAD

**Issue by lsikkes** [sahana/eden#1481]
We are a group of 4 students that are doing a Software Architecture project and we are analysing the Sahana Eden project. We made a technical debt in which we analysed the code and tried to find points which could be improved. The whole document is here [Deliverable3.pdf](https://github.com/sahana/eden/files/1849028/Deliverable3.pdf)

The main points that we analyzed are:
- The project is using Python 2 while the newer Python 3 is out
- The project is not using HTML5 yet
- Some function calls have arguments that are not properly validated, this could lead to security issues
- There are a lot of hardcoded IP addresses, putting these in a config file could increase the security
- There is quite some duplicated code and even duplicated files
- Some minor stuff (can be read in the document)

As part of the project we also want to contribute to the Sahana Eden project.  We were wondering what you think about the debts that we have analyzed and whether you would like to have them implemented. If not we hoped that you could point out something other that we could contribute to. We have about 1.5 week left to do this. We are good programmers but have no experience with the project itself.

**Comment by nursix** [comment]
Please re-sent this to our mailing list sahana-eden@googlegroups.com, thank you.

**Comment by nursix** [comment]
Whilst it is very interesting to read your review, I should probably tell you that we already have multiple such reports as we continuously do our own analysis ;)

Many of your findings lack project context, though - so they fall short of providing actually useful/actionable input, and partially even make incorrect assumptions and hence proposals that should not - or cannot - be followed because they conflict with the project structure/strategy.

We can certainly discuss your document on our mailing list, but it could lead to discouraging feedback if you present your findings as absolute truth without putting them into perspective (...of it lacking project context/strategy insight and thus not necessarily being all correct conclusions).

**Comment by nursix** [comment]
For instance, the "many hardcoded IP addresses" you're referring to are actually all 127.0.0.1 (i.e. localhost), or version numbers - so the recommendation to "put them into a config file" is just nonsense, because that is a well-defined IP address everybody knows and doesn't give anything away. Others are even version numbers (e.g. ExtJS uses 4-part version numbers).

Don't think we don't have static code analysis tools of our own ;)

So, before you run into very bad feedback from very busy developers ;) be careful what statements you make, and validate them in-context.

**Comment by nursix** [comment]
My extended feedback below:

First of all - yes, there is a lot of duplicated code because Sahana Eden is multiple applications (it's a platform, not a monolithic app!) - and in particular static/themes and modules/templates, which represent applications, may contain similar or even equal code. That's deliberate, and a non-issue.

Conversely, there is duplicated /functionality/ - i.e. the same functionality implemented by multiple code variants/patterns, which is typically a consequence of reimplementations-in-transition (or call it "incomplete migrations to newer techniques"). That *is* a problem that definitely needs fixing, but isn't detectable by static code analysis of course (however, it's being worked on).

Yes, Sahana Eden is still Python-2.7, but that's not necessarily wrong. Of course, we do want to gradually move to Python-3 in the coming years, but we will of course have to wait for all our dependencies to have completed that transition (in particular web2py, where Py3 support has entered maintenance stage only recently), and we also have a responsibility to be backwards-compatible with existing Python-2.7 deployments and thus the transition effort will be a little more than a simple code analysis would suggest. There is no urgency with that whatsoever, Python-2.7 works just fine and will still do so for a number of years.

However, we have only recently removed all print-statements from all active/critical parts of the code (although historic/inactive code and 3rd party code may still contain some), as a step into the direction of Python-3 - and banned their re-introduction in our developer guidelines.

Similar, marking the absence of HTML5 format as major issue while our layout frame declares XHTML-1.0-Transitional as DOCTYPE isn't exactly proper analysis ;) Of course, if the need arises to use new XHTML-5 elements, then changing the DOCTYPE would make sense, but without that need, what's the problem? HTML-5 may have dropped some HTML-4 elements/attributes, but that doesn't mean browser support for them hasn't suddenly stopped too. The relevance of this "issue" is certainly not major, and unlikely to ever become so.

Similar with JS analysis, e.g. a "failure to assign a default value to a variable" with the consequence of it potentially being undefined is totally acceptable and may even be deliberate - there is almost no point to this being mentioned as an issue, and I would even put the tool in question that reports it as a "major".

But what is more important is that not all JS components are genuine Sahana Eden - we include a significant amount of 3rd party code in our repo (e.g. ExtJS, jquery, NVD3), which may or may not have weaknesses, but we would still not fix them but leave that to the respective developer community and rather upgrade to newer versions as/if available and necessary than to patch our included copies (which is a really bad idea from a code maintenance point of view). Obviously, code analysis must differentiate between genuine Eden code, and 3rd party code, in order to be anyhow useful/actionable for us.

That same applies for active/core code vs. inactive/historic code vs. code examples/templates. The truly relevant parts of the code that affect some or all of the currently maintained application templates must be separated from the historic/unused parts - otherwise the analysis says very little about the current status of the platform.

And code examples/templates must be treated in yet another way because those are often not meant to run without modifications (some would e.g. not contain any active code but just comments), and yet the parts that wouldn't normally be modified or even copy/pasted around should be verified and clean - and even more so than core code because these parts are used by inexperienced programmers and *meant* to be replicated many times.

That is why we perform static code analysis in a more differentiated fashion, so that it doesn't overwhelm us with irrelevant numbers, but highlights the real, relevant problems and gives us actionable input rather than unreflected stats and rankings without any real meaning, priority or focus.

And finally, as for testing - the value of the mythical "100% test coverage" is debatable, and in our case neither meaningful nor feasible. Our automatic testing priority is critical regressions (S3 core) and complex regressions, which is sufficiently covered by our set of unit and smoke tests.

Deployment feedback shows a very low actual failure rate (<3 per year and template), so that we have some evidence that this works. Of course those deployments are all professionally supported, so that we can assume many issues are caught pre-production - but I haven't heard of any critical failures there either as far as actively maintained modules/templates are concerned.

So, this automated testing strategy plus human peer-review of all submitted code is what we found to have the best cost-benefit ratio for our project, and I don't think some static code analysis can prove otherwise.

Professional service providers who have a need for more in-depth functional testing can additionally use the EdenTest *framework* (!) to implement automated verification for their requirements. We provide only the testing framework, some tools and a few example test cases, so consequently, your finding that these example test cases are not very exhaustive/useful is only natural - we have no intention to make them more than what they are: examples, easy to copy and adapt.

In addition to what the core project does re:QA, most professional deployers additionally conduct more or less comprehensive pre-production tests in their target server environments - and in many cases, we get their feedback too (as you can see on the GitHub issues list resp. commits history).

Fixing their problems (or merging their fixes) is of course much more worthwhile than fixing potential issues found by rule-based analysis tools with no or very little evidence of practical impact (we do fix them too, but with much lower priority).

----

So, all in all, my recommendation for you would be to analyze your analysis again, and maybe refine the methodology and adapt it a little to the actual project context (which we can help you with if you post to our mailing list), so that your efforts yield more useful and actionable recommendations.

Also, I'd recommend to cut out the rankings - they mean very little and may even be misleading both for your own learning, and for ours. Useful input just doesn't look like "C+" ;)

And finally, it would be a valuable contribution from your side to, instead of your "findings", provide meaningful strategies (and maybe tools+configuration files) for /differentiated/ static code analysis that we can deploy on e.g. Travis CI and which gives us relevant, actionable feedback upon commits and pull requests. Since you have experience with the tools, and given my feedback above for amending your strategy, maybe you could use your time to work on that?

Best wishes,
Dominic

**Comment by nursix** [comment]
Besides, it seems that you have examined a little more than Sahana Eden here.

For instance, applications/admin/controllers/appadmin.py is /not/ Sahana Eden (but web2py). You should limit your analysis to applications/eden.

Another "vulnerability" you meantioned...Sahana Eden has exactly 1 instance of eval() in an unused widget class, otherwise the statement isn't used - neither in Python nor in JS. So, your statement on that simply isn't true.

Also, I don't see the point in your comment on this:
```
if($('#' + json['id']).length === 0 || json['force'] === true)
```
...your analysis of this like of code doesn't match the semantics of this piece of code in any way, the code analysis leading to your statement is obviously wrong.

Then this:
```
Method "init" has 16 parameters, which is greater than the 7 authorized. 
```
...is obviously arbitrary - how many parameters you authorize is entirely up to you.

There are a number of other false statements or incorrect analysis, which discredit your report. You will probably want to validate and re-assess those before you submit your report to someone who relevant for your grades ;) this looks rather sloppy.

**Comment by flavour** [comment]
jshint:
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/EdenMobile/DevelopmentEnvironment

**Comment by nursix** [comment]
Locally I'm using PyLint/jshint as well as Xalan resp. Eden's csv2xml/xls2xml (for XSLT transformation).

What I could imagine to deploy on CI is a diff-based Py/JS checker (i.e. checking all modified files), that can report certain selected errors/warnings (we do not want all possible warnings/errors, nor any pointless statistics). It should also be possible to fail the check on some errors, but not others.

Note that PyLint will need to be executed in the web2py environment, otherwise most imports will fail (web2py uses a custom importer).

We do have a travis configuration already, so perhaps something could just be added to that (jshint can for sure, but less certain how to do that with PyLint).

**Comment by lsikkes** [comment]
I am currently trying to create a configuration for JShint and I still have a few questions. 

First of all, is there a designated place where you store all your javascript files? I see that most of them are in the static/scripts directory, but I also see a lot of external files here like jquery and datapicker stuff, which should not be tested, right? 

Secondly you mentioned that you only want certain selected errors/warnings and not all possible warnings. Could you be a bit more specific about this? Also since you say that you use it locally, do you have a configuration file that you could share?

**Comment by nursix** [comment]
Sorry, I missed your last reply - I had closed this issue and asked to move the conversation to the mailing list as that would reach a wider audience as appropriate for such a discussion.

But anyway - yes, I do have a .jshintrc which I could share, but .jshintrc in general is trivial, and since we should anyway be able to adapt it to our needs, you can as well start with a default one.

My example:
```
{
  "undef": true,
  "unused": true,
  "globals": {
    "jQuery": false,
    "S3": true,
    "S3ClearNavigateAwayConfirm": true,
    "s3_debug": true,
    "d3": false,
    "nv": false,
    "i18n": true,
    "$": false,
    "confirm": false,
    "console": false,
    "OpenLayers": false,
    "moment": true
  },
  "browser": true
}
```

Obviously we would want the ```browser``` option enabled, and some standard globals declared (such as jQuery, window, console and S3) to get rid of unnecessary "undefined variable" messages - but you would find out very quickly anyway, so no need to elaborate on that here.

What is more important is to decide which files to check (only modified files, no minified files), and when to report and when to ignore an error reported by jshint. These two things must be configurable, but they can't be configured in .jshintrc - so they would have to be configured in the calling shell script.
