### ISSUE TITLE
Homepage Menu Grid Optimization 

### ISSUE THREAD

**Issue by osakuek** [sahana/eden#1484]
The Menu Grid on the default Sahana homepage is kind of cramped. Some of the words are overlapping for certain screen sizes.
![before padding change](https://user-images.githubusercontent.com/31481773/38472907-ffbb68e4-3b54-11e8-8a79-137b2c53c913.png)
 As you can see, Organizations and Commitments overlap with the icon texts next to them. I think it would be nice to separate them out a little bit. I've actually found a way to fix this but I wanted to report it first.

**Comment by osakuek** [comment]
Changes made to index.html with this result: ![screenshot from 2018-04-03 17-05-32](https://user-images.githubusercontent.com/31481773/38472942-7c957602-3b55-11e8-818d-87d69a67b37d.png)

**Comment by nursix** [comment]
This seems to replace one problem with another, though - your second screen shot shows the grid elements partially overlapping (blanking out) the organizations box.

Question is whether this is a useful problem report at all - if you say "certain screen sizes", then what screen sizes are you referring to - and do these screen sizes actually exist (which end devices)?

**Comment by nursix** [comment]
It seems that the problem was that the grid items were not properly wrapped, so that their effective width was determined by the icon alone. Fixed with the above.

I've also changed the icon-bars to four-up (instead of five-up) - which allowed me to extend the width of the left part from 5 to 6 columns, automatically improving the spacing of the items.

So, now it shouldn't be possible for the labels to overlap anymore.
