### ISSUE TITLE
Precedence-Header in mass mailings

### ISSUE THREAD

**Issue by frommberger** [sahana/eden#1485]
To ensure delivery and inboxing of Eden-generated emails, it would be very beneficial to include "Precedence: bulk" in the mail headers if the number of recipients exceeds a certain number. This indicates the mail is part of a bulk mailing, increasing the sender's credibility. (For example, refer to Google's strategies to detect spam mails: https://support.google.com/mail/answer/81126?hl=en)

Setting an additional header is trivial:
https://github.com/sahana/eden/blob/ff5c2904015c1f26b2736e677260ce6961a5b9f5/modules/s3/s3msg.py#L984

It might be a good idea to add "header" as an additional parameter to the routines. For example, in deployed alerts, the header could/should always be set:
https://github.com/sahana/eden/blob/ff5c2904015c1f26b2736e677260ce6961a5b9f5/modules/s3/s3msg.py#L839

Comments?

**Comment by nursix** [comment]
I don't think this can completely eliminate the need for a registered relay host, but it _could_ additionally improve things. 

Ideally, the bulk-situation would be auto-detected from the number of recipients in the message (i.e. in send_by_pe_id) rather than making it dependent on the purpose of the email.

Feel free to send a pull request to further discuss the implementation of it - if it is easy as you say, then certainly fine to include in Sahana.

However - as I have stated before: mass mailing (and the corresponding subscription management) should ideally be outsourced to list servers rather than letting Sahana produce and sent many individual messages via send_by_pe_id. That's not only for the prevention of SPAM-blacklisting, but also for better scalability and reliability (including automatic re-send, catching replies etc etc).

There is no reason why Sahana should be extended with complex functionality those list servers have provided for decades, and much better than Sahana could with any reasonable effort. We really should prioritize better integration with such list servers over trying to re-invent them.

**Comment by flavour** [comment]
(1) That linked Google article no longer mentions the Precedence Header, so seems like something which has fallen by the wayside
(2) Am not really sure where we'd use it since I believe all of our email messages end up being To: a single recipient
Am closing for now, but will happily reopen if there is utility
