### ISSUE TITLE
<type 'exceptions.TypeError'> 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by bienxennethia** [sahana/eden#1502]
I am always getting this issue can anyone help me? Thank you in advance!

Traceback (most recent call last):
  File "C:\Users\Dell 5421\web2py\gluon\restricted.py", line 227, in restricted
    exec ccode in environment
  File "C:/Users/Dell 5421/web2py/applications/eden/controllers/org.py", line 505, in <module>
  File "C:\Users\Dell 5421\web2py\gluon\globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "C:/Users/Dell 5421/web2py/applications/eden/controllers/org.py", line 149, in facility
    return s3db.org_facility_controller()
  File "applications\eden\modules\s3db\org.py", line 7234, in org_facility_controller
    rheader = org_rheader,
  File "C:/Users/Dell 5421/web2py/applications/eden/models/00_utils.py", line 244, in s3_rest_controller
    output = r(**attr)
  File "applications\eden\modules\s3\s3rest.py", line 683, in __call__
    output = self.resource.crud(self, **attr)
  File "applications\eden\modules\s3\s3rest.py", line 1767, in __call__
    output = self.apply_method(r, **attr)
  File "applications\eden\modules\s3\s3crud.py", line 104, in apply_method
    output = self.create(r, **attr)
  File "applications\eden\modules\s3\s3crud.py", line 400, in create
    format=representation,
  File "applications\eden\modules\s3\s3forms.py", line 1095, in __call__
    *formfields)
  File "C:\Users\Dell 5421\web2py\gluon\sqlhtml.py", line 1809, in factory
    **attributes)
  File "C:\Users\Dell 5421\web2py\gluon\sqlhtml.py", line 1286, in __init__
    inp = field.widget(field, default)
  File "applications\eden\modules\s3\s3widgets.py", line 4670, in __call__
    country=values.get("L0"),
  File "applications\eden\modules\s3\s3widgets.py", line 4937, in _labels
    d[int(level[1:])] = s3_str(T(row[level]))
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by flavour** [comment]
Please confirm that you are running the latest trunk revision of code (it appears not as what is line 4937 in your traceback is line 5076 in trunk)
Please let us know which template are you are running.
Please provide the URL you are accessing & explain what you are trying to do when this happens.
It looks like the URL /eden/org/facility/create, so you are trying to create a Facility...the crash is in the Location Selector.
My first guess therefore is that the issue is that you haven't run prepop properly for the template you are trying to run, so please confirm that prepop completed successfully:
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/PrePopulate

If you confirm which template you are running then I can check here whether that template can create Facilities or not in current trunk with prepop run properly.

**Comment by flavour** [comment]
I can confirm that /eden/org/facility/create works for me in current trunk with prepop running OK.
Other things to look at are:
* Python revision (We should support 2.7 & 3.x...I tested with 2.7)
* Web2Py revision (Should ideally be 2.18.3-stable)

**Comment by bienxennethia** [comment]
I am using settings.base.template = "default" as a template. python 2.7 and web2py 2.18 still got that error.

**Comment by flavour** [comment]
You don't confirm the URL you are accessing.
More importantly, you don;t confirm that prepop runs correctly.
If it does then it /could/ be a bug in that revision of code, so suggest updating to current trunk.

**Comment by bienxennethia** [comment]
this is the url I am accessing http://127.0.0.1:8000/eden/org/facility/create

**Comment by hallamoore** [comment]
I'm getting a similar error, but for `/eden/org/organisation/1/office` instead. I just cloned the eden and web2py repos, so they should be up-to-date. I did not do any pre-populating, but I manually created a few organizations. 

I clicked an "Open" button next to one of the organizations which took me to `/eden/org/organisation/1/update`. I tried clicking on the "Offices" tab from that page, which directed me to `eden/org/organisation/1/office`. That resulted in the error. 

I also get the same error if I try accessing the "Warehouses" or "Facilities" tabs. The "Assets" tab doesn't work either, but that has a different error. The "Staff & Volunteers" and "Projects" tabs do work, showing an empty table and an option to create rows. 

Is the expected behavior for the erroring tabs (when there has been no prepopulation) that an empty table should show up, as it does for "Staff & Volunteers" and "Projects?

**Comment by nursix** [comment]
It is a common mistake to replace the prepopulate-setting in the template rather than adding to it, thereby removing the mandatory import of the SITE_DEFAULT gis_hierarchy:

```
settings.base.prepopulate = [...]   # wrong!
settings.base.prepopulate += [...] # correct!
```

This isn't currently caught, see comments in #1511 to learn why and how it should ideally be handled. In the meantime, you can fix the problem in your deployment by fixing the prepop-setting. Make sure that you import at least one gis_hierarchy.csv that contains the SITE_DEFAULT (e.g. modules/templates/default/base/gis_hierarchy.py, which is part of the "default/base" prepop).

**Comment by nursix** [comment]
Besides, you cannot run Sahana entirely without prepop. There are some mandatory prepop data which your template must provide, by importing either "default/base" or suitable alternatives.

We should not catch errors that are caused by an invalid setup - anywhere except during first run.
