### ISSUE TITLE
GIS config missing

### ISSUE THREAD

**Issue by hallamoore** [sahana/eden#1513]
The form at `eden/org/office/create` isn't displayed when there is no GIS config. There weren't any errors displayed on the webpage, but with a pdb breakpoint in the application I eventually checked out `s3db.org_office_controller()['form'].xml()` and saw an HTTP 303 printed. The pdb session wasn't enough to get a traceback, but I was able to get one by opening a `code.interact` session within the pdb session and running the same thing. There were a bunch of recursive xml calls, but the bottom of the traceback looks like:

```
File "applications/eden/modules/s3/s3gis.py", line 7124, in xml
  result = self._setup()
File "applications/eden/modules/s3/s3gis.py", line 6443, in _setup
  redirect(URL(c="default", f="index"))
File "/home/halla/sahana-eden/web2py/gluon/http.py", line 182, in redirect
  **headers)
HTTP: 303 SEE OTHER
```

So it appears that my GIS config is missing.

Question 1: 
How do I include a GIS config? I tried switching my `settings.base.prepopulate` to `["default"]`, but that resulted in a bunch of `gis_layer_config: config_id: value(s) required` lines, and no change in behavior for the form.

Question 2:
Similar to how we included a default hiearchy in #1512, is there some default I could try to implement here? (Maybe not, I don't know what all is included with the GIS config, so maybe a default doesn't make any sense. Which leads to question 3...)

Question 3:
It looks like there's a `current.session.error = current.T("Map cannot display without prepop data!")` line right before the redirect, but I only see this error message when I
navigate to the next page. Is there a way to get this to appear on the current page?

**Comment by nursix** [comment]
Rephrasing the problem:

The map cannot be shown without a GIS config - which is simply because the GIS config determines what is to appear on the map (e.g. which base layer).

That no GIS config is provided during prepop is not wrong - the system administrator may choose to not import one during prepop, but create one interactively instead. Until they do so, of course, the map cannot be displayed - but the system will work without crashing, and that is where it differs from #1512.

Thus, the correct response of the system to a missing gis_config is indeed be to indicate that no map can be displayed unless/until a gis_config is created.

---

As for your questions:

Q1: a standard basic gis_config (along with a bunch of layers) is provided by the "default/base" prepop - which is in the settings.base.prepopulate setting by default. If you extend the setting (```+=```) rather than overriding it (```=```), you shouldn't have any problems with that.

If you override the setting, then you can include "default/base" as first element of the array.

Q2: I don't think so. Omitting a default gis_config is a valid choice (unlike omitting the SITE_DEFAULT gis_hierarchy, which breaks code) - but if you omit it, of course you must accept that no map can be shown.

Q3: This is the real thing to fix here. IMHO the error message should appear **in place** of the map (i.e. inside the same container element), and no redirect should happen at all.

The redirect is risky, because there is no safe page to go to. Even default/index can contain a map, and redirecting to that will thus lead into a redirect loop. And out of principle, low-level framework functions should never redirect, not ever - they should either raise or return the error and let the caller catch it and decide what to do, or they should default in some meaningful way.

If the map cannot be rendered due to a missing config, then I think the page should still be rendered normally, but in the place of the map there should be the error message saying that no map can be constructed without a config - potentially with a link to the config editor (if the user has permission to create one).

**Comment by nursix** [comment]
My suggestion here would be:

If no gis_config is found here:
https://github.com/sahana/eden/blob/master/modules/s3/s3gis.py#L6440

...then do not redirect, but set a `self.error_message` (must be initialized in `__init__` of course) and return `None`. Then, here:

https://github.com/sahana/eden/blob/master/modules/s3/s3gis.py#L7125

...check for `self.error_message` - and if there is one, render it (using `self.append`) and return `super(MAP, self).xml()` immediately. If there's no error message, `return ""` as it was.

**Comment by nursix** [comment]
Of course, that suggestion is just an idea - you will have to test whether it really works (incl. UX).

**Comment by flavour** [comment]
I don't disagree with anything Dominic is saying, but just for your information:

> It looks like there's a `current.session.error = current.T("Map cannot display without prepop data!")` line right before the redirect, but I only see this error message when I
> navigate to the next page. Is there a way to get this to appear on the current page?

If there wasn't a redirect then to have the error appear on the same page, the usual solution is to use current.response.error (session.error gets copied there during the new page rendering process)

In this case, though, I agree that the error being within the Map DIV is a better solution.

**Comment by hallamoore** [comment]
Thanks for the information and suggestion! I'll see what I can do

**Comment by hallamoore** [comment]
> potentially with a link to the config editor (if the user has permission to create one)

Where is the config editor? I looked under some of the admin settings, but didn't see anything that I recognized as being GIS related. 

Also, I sorta want to update the error message so that it says `Map cannot display without a GIS config` instead of `without preprop data`, but how does that work with translation? Would I need to manually update the language files?

**Comment by flavour** [comment]
> Where is the config editor? I looked under some of the admin settings, but didn't see anything that I recognized as being GIS related.

/eden/gis/config

> Also, I sorta want to update the error message so that it says `Map cannot display without a GIS config` instead of `without preprop data`, but how does that work with translation? Would I need to manually update the language files?

I would just update the string.
If you are removing an older string, you /could/ remove the orphaned translations.
If you happen to speak other languages then feel free to translate the new error, but a setup error like this is very low priority to translate.
