### ISSUE TITLE
Shapely geos IllegalArgumentException

### ISSUE THREAD

**Issue by waidyanatha** [sahana/eden#1526]
I git cloned eden from sahana repo. Then changed 000_config template to "SAMBRO" and ran 'clean' from /usr/local/bin. All the imports except for the SAMBRO/Demo sub template

Importing SAMBRO/Demo...
ERROR:shapely.geos:IllegalArgumentException: Points of LinearRing do not form a closed linestrin

produced 8 lines of the same error 
Imports for SAMBRO/Demo complete (193.03 sec)

did some basic navigation and seems to work but NOT SURE whether it may affect some isolated function or feature?

**Comment by flavour** [comment]
On Mon, 2 Dec 2019 at 08:25, Nuwan Waidyanatha <notifications@github.com> wrote:
> I git cloned eden from sahana repo. Then changed 000_config template to "SAMBRO" and ran 'clean' from /usr/local/bin. All the imports except for the SAMBRO/Demo sub template
> Importing SAMBRO/Demo...
> ERROR:shapely.geos:IllegalArgumentException: Points of LinearRing do not form a closed linestrin

So this is saying that 1-8 of the Polygons that you are importing in
the demo data don't seem to be correct:
https://shapely.readthedocs.io/en/stable/manual.html#linearrings

If you want to see which of the polygons, then run the import in Debug
mode & it should give you more info as to which file is at issue and
then you can try each polygon in the file.

> did some basic navigation and seems to work but NOT SURE whether it may affect some isolated function or feature?

Just that data will be affected.

F

**Comment by waidyanatha** [comment]
Thanks for the explanation. I might have also triggered it trying to play with gis_config.py in the sub template - in my attempt to give map focus to a particular country, Fiji in this case. I need to study that further.

**Comment by flavour** [comment]
I investigated the data from the Philippines feed, e.g.:
http://publicalert.pagasa.dost.gov.ph/output/gfa/7f251b56-83b4-46f3-8ded-0236731fb731.cap

I then cross-checked the standard (http://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2-os.html)
1.5    Terminology
The term “coordinate pair” is used in this document to refer to a comma-delimited pair of decimal values describing a geospatial location in degrees, unprojected, in the form “[latitude],[longitude]”
3.2.4    "area" Element and Sub-elements
(2) A minimum of 4 coordinate pairs MUST be present and the first and last pairs of coordinates MUST be the same.

However the polygons in the feed don't match either of these requirements:
(1) The pairs are Lon,Lat not Lat,Lon
- so our imports place the polygons on the wrong place on the map
(2) The first and last pairs of coordinates are not the same, so we import a LINESTRING instead of a POLYGON (We do actually catch this potential issue already, so the data provided *is* imported even if it's incorrect in these 2 aspects

**Comment by waidyanatha** [comment]
Should we bring this to the attention of PAGASA?

**Comment by flavour** [comment]
Yes, I think that would be a good idea, you have their contacts right?
