### ISSUE TITLE
ValueError: day is out of range for month

### ISSUE THREAD

**Issue by Billarhos** [sahana/eden#1537]
Hi, after running Sahana in windows 10 64 bit with Windows/Developer/Installer i caome to the following error.
`File "applications\eden\modules\s3\s3fields.py", line 1166, in s3_date
    min = now.replace(year=current_year - past_years, month=past_month)
ValueError: day is out of range for month`

How can i overcome this issue?

**Comment by flavour** [comment]
This looks like a very old version of Sahana (5 years old+).
s3_date now uses dateutil.relativedelta to avoid this leap year bug

**Comment by Billarhos** [comment]
Thank you @flavour
I think this is due to 29 of February date i run it. Now it is running. Is there any newer windows installation?

**Comment by flavour** [comment]
> I think this is due to 29 of February date i run it.

yes

> Now it is running. Is there any newer windows installation?

Since you are using the Developer install, then I assume you are a developer.
You can upgrade the code to the latest just using Git, but is you used an old Windows installer then all the libraries will be old too, so better to just install the latest versions.
You can see which ones are needed/useful by looking at requirements.txt & optional_requirements.txt
